feat: extend fiveg_rfsim interface
canonical/oai-ran-du-k8s-operator pull request #64
Opened 2024-12-03 12:15 UTC by gatici

# Description

This PR extends the fiveg_rfsim interface according to https://github.com/canonical/charm-relation-interfaces/pull/202 by putting RFSIM address, SST and SD information to the relation data bag.

- Validates Provider application data before putting the information to the relation data bag
- Removes custom events and only uses standart charm events (relation joined, relation changed) to simplify the implementation
- Expand unit tests for fiveg_rfsim interface

# Dependencies

The implementation in the charm depends on fiveg_f1 interface as this interface is used to get the SST and SD data from CU charm. fiveg_rfsim relation should wait until data is  retrieved through fiveg_f1 relation. https://github.com/canonical/oai-ran-du-k8s-operator/pull/58 should be merged.

# Note
fiveg_f1 interface can carry multiple PLMNs and each PLMN includes SST and SD.
Which SST and SD value should be sent to UE in the fiveg_rfsim relation data ? 
After discussing this with @Gmerold , TE126 updated to use the first PLMN. 
Fiveg_rfsim interface only used with UE simulator. 
For real UE's, device group of slice includes the IMSI which can be associated with the related UE. 

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2024-12-03 15:00 UTC, gatici commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +    def sst(self) -> Optional[str]:
I added those properties temporarily to call the `self.rfsim_provider.set_rfsim_information` method. I know that the implementation in the charm should be changed after your PR merged.

2024-12-09 15:31 UTC, ghislainbourgeois approved these changes

2024-12-09 15:40 UTC, patriciareinoso requested changes

2024-12-09 15:40 UTC, patriciareinoso commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +    def sst(self) -> Optional[str]:
```suggestion
    def sst(self) -> Optional[int]:
```

2024-12-09 15:40 UTC, patriciareinoso commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +    def sd(self) -> Optional[str]:
```suggestion
    def sd(self) -> Optional[int]:
```

2024-12-09 15:50 UTC, patriciareinoso commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +    def sst(self) -> Optional[str]:
this comment is still valid.

2024-12-09 15:54 UTC, gatici commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +    def sd(self) -> Optional[str]:
Done

2024-12-09 15:57 UTC, gatici commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +    def sst(self) -> Optional[str]:
This is fixed with the latest commit.

2024-12-09 15:58 UTC, gatici commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +    def sst(self) -> Optional[str]:
Thank you!

2024-12-10 12:30 UTC, patriciareinoso requested changes

2024-12-10 12:30 UTC, patriciareinoso commented on src/charm.py
> +        self.framework.observe(self.on[RFSIM_RELATION_NAME].relation_joined, self._configure)
I think that we can observe relation-changed events

2024-12-10 12:33 UTC, patriciareinoso commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +            str: sd (Network Slice Differentiator)
```suggestion
            Optional[int]: sd (Network Slice Differentiator)
```

2024-12-10 12:34 UTC, patriciareinoso commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +            str: sst (Network Slice Service Type)
```suggestion
            Optional[int]: sst (Network Slice Service Type)
```

2024-12-10 12:34 UTC, patriciareinoso commented on lib/charms/oai_ran_du_k8s/v0/fiveg_rfsim.py
> +            str: rfsim address which is equal to DU pod ip.
```suggestion
            Optional[IPvAnyAddress]: rfsim address which is equal to DU pod ip.
```

2024-12-10 13:16 UTC, patriciareinoso approved these changes

2024-12-10 13:32 UTC, patriciareinoso approved these changes

2024-12-10 14:35 UTC, merged